#!/bin/bash

if [ -d ./dashenv ]
then
  source ./dashenv/bin/activate
else
  python3 -m venv dashenv
  source ./dashenv/bin/activate
  pip install --no-cache-dir --update pip
  pip install --no-cache-dir -r requirements.txt
fi

python app.py
